/**
 * The card photographs' index (spec 2026-09-16 §4): one licensed WebP per
 * deep-sky object, planet, the Moon, the ISS and the Milky Way, plus (task
 * 19, ruling R25) one artwork per constellation whose card tells a myth, generated by
 * scripts/prepare-sky-images.mjs. Same gate as objects.json: a 404 resolves
 * null and cards simply carry no photograph; a malformed index throws, which
 * NightSky logs at the component boundary. The photographs themselves load
 * only when a card opens (SkyCard's <img loading="lazy">), never here.
 */
import { gate } from "./sky-objects";

export type SkyImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  author: string;
  license: string;
  licenseUrl: string;
  sourceTitle: string;
  sourceUrl: string;
  sha1: string;
  /** Set only when the pick list's `crop` narrowed the source frame (fix
   *  round #2): CC BY / CC BY-SA ask that a modification be disclosed, and
   *  the card's credit line reads this to add ", cropped and resized" in
   *  place of the plain ", resized" every entry gets. */
  cropped?: true;
  note?: string;
  /** Task 19 (R25): set only on a myth constellation's image, which is an
   *  artwork (a painting, a vase, a star-atlas plate), never a photograph.
   *  Names it: "Bacchus and Ariadne, Titian, 1520-1523". The card reads its
   *  presence to say "Image:" instead of "Photograph:" and to add the line
   *  that it is an artwork, not a photograph of the sky. */
  artwork?: string;
  /** CSS object-position ("50% 30%") for the card's object-fit: cover box,
   *  so a painting's faces survive the 4:3 / 2:1 frame. Positions only. */
  focus?: string;
};

export type SkyImagesIndex = { version: 1; generated: string; images: Record<string, SkyImage> };

export const IMAGES_URL = "/sky/images/index.json";

const REQUIRED: (keyof SkyImage)[] = [
  "src",
  "width",
  "height",
  "alt",
  "author",
  "license",
  "licenseUrl",
  "sourceTitle",
  "sourceUrl",
  "sha1",
];

export function validateImagesIndex(d: unknown): string | null {
  const x = d as Partial<SkyImagesIndex> | null;
  if (x?.version !== 1) return `version ${String(x?.version)}`;
  if (typeof x.generated !== "string") return "no generated date";
  if (!x.images || typeof x.images !== "object") return "no images map";
  for (const [id, im] of Object.entries(x.images)) {
    for (const k of REQUIRED) {
      if (im == null || (im as Record<string, unknown>)[k] === undefined) return `${id}: missing ${k}`;
    }
    if (!(im as SkyImage).src.startsWith("/sky/images/")) return `${id}: src off-site`;
    const focus = (im as SkyImage).focus;
    if (focus !== undefined && !/^(100|[1-9]?\d)% (100|[1-9]?\d)%$/.test(focus)) return `${id}: bad focus`;
  }
  return null;
}

export const loadImages = gate<SkyImagesIndex>(IMAGES_URL, validateImagesIndex);
